"""add anomalies table

Revision ID: 949c3d58ded6
Revises: f2dec4daee39
Create Date: 2026-08-03 19:30:11.736968

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "949c3d58ded6"
down_revision: str | Sequence[str] | None = "f2dec4daee39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # Existence-guarded: a DB created via Base.metadata.create_all (fresh
    # installs, and the "stamp to baseline then upgrade" path when a
    # current-schema DB replays the chain) already has this table, so an
    # unconditional create_table would collide. Same pattern as the other
    # post-baseline migrations in this directory.
    if inspector.has_table("anomalies"):
        return
    op.create_table(
        "anomalies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("batch_id", sa.String(), nullable=False),
        sa.Column("sample_id", sa.String(), nullable=False),
        sa.Column("target_profile", sa.String(), nullable=False),
        sa.Column("device_serial", sa.String(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("detail_json", sa.Text(), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_anomalies_acknowledged"), "anomalies", ["acknowledged"], unique=False)
    op.create_index(op.f("ix_anomalies_batch_id"), "anomalies", ["batch_id"], unique=False)
    op.create_index(op.f("ix_anomalies_created_at"), "anomalies", ["created_at"], unique=False)
    op.create_index(op.f("ix_anomalies_sample_id"), "anomalies", ["sample_id"], unique=False)
    op.create_index(
        op.f("ix_anomalies_target_profile"), "anomalies", ["target_profile"], unique=False
    )
    op.create_index(op.f("ix_anomalies_type"), "anomalies", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_anomalies_type"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_target_profile"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_sample_id"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_created_at"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_batch_id"), table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_acknowledged"), table_name="anomalies")
    op.drop_table("anomalies")
    # ### end Alembic commands ###
